# Generated by Django 5.0.6 on 2024-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pix',
            field=models.ImageField(default='profile_pix/default.jpg', upload_to='profile_pix/'),
        ),
    ]
